export default {
    detailPage:'صفحة التفاصيل',
    detailScreen:'شاشة التفاصيل',
    english:' EN ',
    arabic:' العربية ',
    naomiImg:'https://storage.googleapis.com/nay/images/web/logo.b9e5f14e.png',
    shopplingBag:'shopping-bag',
    WhatsApp_Click_to_Chat: 'واتس اب انقر للدردشة',
    aboutNayomi:'عن نعومي',
    helpCenter: 'مركز المساعدة',
    text:'',
    appDownload:'تنزيل التطبيق',
    amiraClubSignUp:'أميرة نادي التسجيل',
    storeLocator:'فروعنا',
    nayomiHolidayShop:'نعومي هوليداى شوب هنا!',
    happeningNow:'يحدث الآن @',
    Nayomi:'نعومي',
    customerService:'خدمة العملاء :',
    connectWithUs:'اتصل بنا',
    paymentMethod:'طريقة الدفع او السداد', 
    descriptionHeader:'ملابس داخلية ، ملابس نوم ولانجيري في نعومي: وجهة التسوق عبر الإنترنت لجميع الأشياء الأنيقة وبأسعار معقولة وفي نفس الوقت!',
    descriptionMsg:'سوف تكون قادرًا على الاعتماد على الملابس الداخلية من نعومي لتبدو ساحرة وأنيقة. منتجاتنا ذات قيمة مقابل المال حيث يتم وضع كل التفاصيل تحت الأضواء. استعرض من خلال صفحات موقعنا للوصول إلى مجموعة واسعة من الملابس الداخلية المرغوبة التي ستدهن جسدك. تجلب لك نعومي العديد من الملابس الداخلية النسائية لجميع الأذواق وجميع الأشكال ، وبهذه الطريقة سوف تكون على يقين من أنك لا تخطئ في الدانتيل الصدرية أثناء اختيار للحصول على أفضل دعم. استكشف مجموعاتنا الطازجة والفريدة من مجموعات بيجامة ، فساتين ، العشير الزفاف وغيرها من المجموعات لتعكس أسلوبك الخاص.',
    descriptionMsg0: 'نعومي: وجهة ملابسك الداخلية المثيرة',
    descriptionMsg1: 'هو خيارك الأفضل إذا كنت ترغب في أن تبدو مبهرة وفريدة من نوعها بغض النظر عن وقت النهار أو الليل. تقدم لك نعومي مجموعات أنيقة ومثيرة من الملابس الداخلية المتنوعة والمثالية لكل مناسبة تستمتع بها في حياتك. سواء كنت من مجموعات الملابس الداخلية الفاخرة أو حمالات الصدر المصنوعة من الدانتيل المضغوط أو سراويل داخلية أو ملابس نوم ، فإن القطع الأساسية من ملابسك الداخلية تنتظرك جميعًا في نعومي',
    descriptionMsgShort:'سوف تكون قادرًا على الاعتماد على الملابس الداخلية من نعومي لتبدو ساحرة وأنيقة.',
    seeMore: 'قراءة المزيد',
    seeLess: 'أقرأ أقل',
    descriptionFooter:'© 2019 نعومي. كل الحقوق محفوظة.',
    shopCollection:'مجموعات التسوق  >',
    passwordReset:'إعادة تعيين كلمة المرور',
    emailAddress:'عنوان بريد الكتروني',
    mobile:'المحمول',
    Send:'إرسال',
    SELECT_YOUR_COUNTRY:'اختر بلدك',
    INTERNATIONAL:'دولي',
    UAE:'الإمارات',
    KSA:'المملكة',
    SELECT_LANGUAGE: 'اختار اللغة',
    ARABIC:'عربى',
    ENGLISH:'الإنجليزية',
    SUBMIT: 'خضع',
    needAssistance : 'تحتاج آالى مساعدة',
    delivery: 'التوصيل',
    delivery1: 'توصيل',
    faq: 'ألاسئلة الأكثر شيوعاً',
    contactUs: 'اتصل بنا',
    returnsAndExchanges: 'إرجاع والتبادلات',
    privacyPolicy: 'سياسة خاصة',
    termsAndConditions: 'الأحكام والشروط',
    paymentMethods: 'طرق الدفع',
    brandOverview:'نظرة عامة على العلامة التجارية',
    careers: 'وظائف',
    CUSTOMER_SERVICE: 'خدمة العملاء',
    SUNDAY: 'الأحد',
    THURSDAY: 'الخميس',
    TIME: 'زمن',
    AM: 'صباحا',
    PM: 'مساء',
    CONTACT: 'اتصل',
    SHIPPING: 'الشحن',
    EXPRESS: 'التعبير',
    DAYS: 'أيام',
    FREE_DELIVERY_ON_ALL_ORDERS_ABOVE: 'توصيل مجاني لجميع الطلبات التي تزيد عن 299',
    _1_to_3: '1 إلى 3',
    FIRST_NAME: 'الاسم الاول',
    LAST_NAME: 'الكنية',
    MOBLIE: 'التليفون المحمول',
    EMAIL: 'البريد الإلكتروني',
    BIRTHDAY: 'عيد الميلاد',
    WEDDING_ANNIVERSARY: 'ذكرى الزواج',
    MANDATORY: 'إلزامي',
    REGISTER: 'تسجيل',
    PASSWORD: 'كلمه السر',
    CONFIRM_PASSWORD: 'تأكيد كلمة المرور',
    SIGN_UP: 'سجل',
    SIGN_IN: 'تسجيل الدخول',
    CREATE_AN_ACCOUNT: 'انشئ حساب',
    ACCOUNT_PREFERENCES: 'تفضيلات الحساب',
    SAVE_ADDRESSES: 'حفظ العناوين',
    WISHLIST: 'الأماني',
    ORDER_TRACKING: 'تتبع الطلب',
    SECURE_SIGN_IN: 'تأمين تسجيل الدخول',
    FORGOT_PASSWORD: 'هل نسيت كلمة المرور',
    USERNAME: 'اسم المستخدم',
    TEXT1: 'إذا كنت قد سجلت بالفعل في نعومي ، فقم بتسجيل الدخول هنا.',
    TEXT2: 'سجل مع nayomi.com للاستمتاع بالخدمات الشخصية ، بما في ذلك:',
    REGISTERED_CUSTORMERS: 'العملاء المسجلين',
    CREATE_AN_ACCOUNT1: 'انشئ حساب',
    checkOutAsGuest: 'طلب الخروج كزائر',
    checkOutAsGuest1: 'طلب الخروج كزائر',
    checkOutAsGuestButton: 'تسجيل دخول آمن ',
    style:'قلم المدقة',
    collection:'مجموعة',
    offers:'عروض',
    showAll:'عرض الكل',
    login:'تسجيل الدخول',
    search:'بحث',
    productCode:'كود المنتج',
    cancel: 'إلغاء',
    save: 'حفظ',
    change_password: 'غير كلمة السر',
    acccount: 'الحساب',
    order_history : 'تاريخ الطلب',
    wishlist: 'الأماني',
    logout: 'الخروج',
    profile: 'الملف الشخصي',
    phone_number: 'رقم الهاتف:',
    address_book: 'دليل العناوين',
    view_all: 'عرض الكل',
    TEXT3: 'ليس لديك حاليًا أي إعداد لعناوين الشحن. لإضافة عنوان الشحن ، من فضلك',
    click_me: 'انقر فوق لي',
    your_name: 'اسمك',
    purpose: 'غرض',
    your_comment: 'تعليقك',
    submit: 'خضع',
    write_to_us: 'اكتب لنا',
    direct_contact: 'اتصال مباشر',
    social_media: 'وسائل التواصل الاجتماعي',
    TEXT4: 'أهلا بك. كيف يمكننا مساعدتك؟',
    TEXT5: 'ابحث في أسئلتك هنا ...',
    sizeFit : 'الحجم وصالح',
    bra: 'حمالة صدر',
    panty: 'اللباس الداخلي',
    nightwear: 'نوم',
    slippers:'شباشب',
    welcomeHowcanwehelpyour: 'أهلا بك. كيف يمكننا مساعدتك؟',
    sizeGuide: 'دليل المقاسات',
    returns: 'عائدات',
    legal: 'قانوني',
    unitedArabEmirates: 'الإمارات العربية المتحدة',
    saudiArabia: 'المملكة العربية السعودية',
    kuwait: 'الكويت',
    bahrain: 'البحرين',
    qatar: 'دولة قطر',
    oman: 'سلطنة عمان',
    morocco: 'المغرب',
    order_number: 'رقم الطلب',
    address: 'عناوين',
    address1: 'العنوان 1',
    address2: 'العنوان 2',
    address3: '3 العنوان',
    addressType: 'نوع العنوان',
    primaryAddress: 'العنوان الرئيسي',
    deliver_to: 'يسلم إلى:',
    payment: 'دفع',
    delivery: 'توصيل',
    order_summary: 'ملخص الطلب',
    subtotal: 'حاصل الجمع',
    shipping: 'الشحن',
    cod: 'الدفع عند التسليم',
    total: 'مجموع',
    vat: 'ضريبة القيمة المضافة 5 ٪ وشملت',
    order_status: 'حالة الطلب',
    pay_by_card: 'الدفع عن طريق البطاقة',
    order_status1: 'حالة الطلب',
    payment_summary: 'ملخص الدفع',
    saving: 'مدخرات',
    direction: 'اتجاه',
    color: 'اللون',
    size: 'بحجم',
    qty: 'الكمية',
    inStock: 'في المخزن',
    secureShopping:'التسوق الآمن',
    cashOnDelivery:'الدفع عن الاستلام',
    freeClickCollect:'انقر مجانا وجمع',
    to5DaysDelivery:'3 إلى 5 أيام التسليم',
    youMayAlsoLove: 'قد تحب أيضا',
    bandSize: 'حجم الفرقة',
    cupSize: 'حجم الكوب',
    addToBag: 'أضف الى الحقيبة',
    remove: 'إزالة',
    symbol: '<',
    checkout: 'الدفع',
    TEXT6: 'يرجى ملاحظة ، قد يتغير سعر الشراء النهائي عند تحديد عنوان التسليم وطريقة الدفع.',
    you_may_also_love: 'قد تحب أيضا',
    bag_empty: 'حقيبتك فارغة',
    filterBy: 'مصنف بواسطة',
    sortBy: 'ترتيب حسب',
    yes:'نعم فعلا',
    no: 'لا',
    out_of_stock_items: 'من المخزون العناصر',
    remove_these_items: 'إزالة هذه العناصر',
    product: 'المنتج',
    quantity: 'كمية',
    status: 'الحالة',
    shopping_bag: 'كيس التسوق',
    proceed: 'تقدم',
    placeOrder: 'مكان الامر',
    address_information: 'معلومات العنوان',
    saved_addresses: 'saved_addresses',
    add_new_address: 'أضف عنوانا جديدا',
    outStock: 'الأسهم خارج',
    alertQtySizeMsg1: 'هذا المنتج لديه الحد الأقصى للكمية المطلوبة من',
    alertQtySizeMsg2: ' يرجى تحديث الكمية التي اخترتها لتكون ضمن هذا الحد. لكمية الطلب أكثر من',
    alertQtySizeMsg3: ' الرجاء التواصل معنا. ',
    readMore: 'قراءة المزيد',
    readLess: 'أقرأ أقل',
    buymore_savemore: 'شراء أكثر ، حفظ أكثر',
    buyMore: 'اشتري اكثر,',
    saveMore: 'احفظ أكثر',
    discoverMore: 'إكتشف أكثر',
    for: 'إلى عن على',
    imagePreviewNotAvailable: 'معاينة الصورة غير متوفر',
    sar: 'صار',
    aed: 'درهم‎',
    usd: 'دولار أمريكي',
    editAddress: "تعديل العنوان",
    addAddress: "اضف عنوان",
    addnewAddress: "اضف عنوان شحن جديد",
    delete: "حذف",
    edit: "تصحيح",
    updateAddressToster: "تم تحديث العنوان بنجاح",
    addAddressToster: "تمت إضافة العنوان بنجاح",
    deleteAddressToster: "تم حذف العنوان بنجاح",
    videoDownloaded: 'تم تنزيل الفيديو بنجاح',
    postal_code: ' االرمز البريدي ',
    color: 'اللون :',
    size: 'بحجم :',
    free: 'حر',
    percentageSymbol: '٪',
    now: 'الآن',
    was: 'كان',
    saving: 'إنقاذ',
    shoppingBag: 'كيس التسوق',
    click_collect: 'انقر وجمع',
    home_delivery: 'توصيل منزلي',
    contact_information: 'معلومات للتواصل',
    TEXT7: 'الحقل مع علامة',
    TEXT8: 'مطلوبة',
    TEXT9: 'أي تغييرات تجريها ستعمل تلقائيًا على تحديث دفتر العناوين الخاص بك في حسابك.',
    payment1: 'دفع',
    confirmation: 'التأكيد',
    include: 'شمل', 
    TEXT10: 'عن طريق وضع طلبك ، فإنك توافق على موقعنا',
    privacyCookiePolicy: 'سياسة الخصوصية وملفات تعريف الارتباط',
    and: 'و',
    TEXT11: 'غير قادر على معالجة طلبك. يمكنك إعادة المحاولة أو الاتصال بوكيل خدمة العملاء للحصول على مزيد من المعلومات ..',
    TEXT12: 'لقد تلقينا طلبك ، ستتلقى رسالة تأكيد عبر البريد الإلكتروني قريبًا ..',
    sorry: 'آسف',
    thankyou: 'شكرا',
    TEXT13: 'إذا كان لديك أي استفسارات ، فاتصل بخدمة العملاء عن طريق الاتصال بنا على +971 4 3576754 أو إرسال بريد إلكتروني إلينا إلى customerservice@nayomi.com',
    address: 'عنوان',
    order_date: 'تاريخ الطلب',
    order_number1: 'رقم الطلب',
    shipping_type: 'نوع الشحن',
    payment_type: 'نوع الدفع',
    order_total: 'الطلب الكلي',
    TEXT14: 'لديك لم تشتر أي شيء حتى الآن',
    more: 'أكثر من',
    remeber_me: 'تذكرنى',
    sign_up_now: 'أفتح حساب الأن',
    sale: 'تخفيض السعر',
    mada_bank_card_credit_card: 'بطاقة مدى البنكية/البطاقة الائتمانية ',
    notInternational: 'غير متوفر الشحن الدولي',
    registerNow: 'سجل الان',
    toOurVipClub: 'لنا نادي VIP',
    vipDiscount: 'خصومات VIP | أعياد الميلاد',
    privateEvents: 'المناسبات الخاصة والمبيعات | والكثير الكثير',
    ok: 'حسنا',
    cancel: 'إلغاء',
    signInSuccess: 'لقد نجحت في تسجيل الدخول',
  }; 