export default {  
    detailPage:'Detail Page',
    detailScreen:'Detail Screen',
    english:' EN ',
    arabic:'  العربية ',
    naomiImg:'https://storage.googleapis.com/nay/images/web/logo.b9e5f14e.png',
    shopplingBag:'shopping-bag',
    WhatsApp_Click_to_Chat: 'WhatsApp - Click to Chat',
    aboutNayomi:'About Nayomi',
    helpCenter: 'Help Center',
    appDownload:'App Download',
    amiraClubSignUp:'Amirah Club Sign Up',
    storeLocator:'Store Locator',
    nayomiHolidayShop:'Nayomi Holiday Shop is here!',
    happeningNow:'Happening now @',
    Nayomi:'Nayomi',
    customerService:'Customer Service :',
    connectWithUs:'Connect with us',
    paymentMethod:'Payment Method',
    descriptionHeader:'Lingerie, Nightwear and Loungewear at Nayomi:Your online shopping destination for all things stylish, affordable and à la mode!',
    descriptionMsg:'You will be able to count on Nayomi`s lingerie to look glamourous and elegant.Our products are value for money where every detail is put under the spotlight. Browse through the pages of our site to access a wide range of desirable lingerie that will sublimate your body.Nayomi brings you a multitude of women`s lingerie for all tastes and all forms, that way you will be sure not to go wrong with a lace bra while opting for the best support. Explore our fresh and unique ranges of pajama sets, dresses, bridal intimates and other collections to reflect your own style.',
    descriptionMsg0: 'Nayomi : Your sexy lingerie destination',
    descriptionMsg1: 'Nayomi is your best choice if you wish to look dazzling and unique whatever the time of day or night. Nayomi offers you stylish and sexy collections of lingerie varied and ideal for every occasion you experience in your life. Whether you are fancying lingerie sets, push-up lace bras, panties or nightwear, the essential pieces of your lingerie await you all in Nayomi.',
    descriptionMsgShort:'You will be able to count on Nayomi`s lingerie to look glamourous and elegant.',
    seeMore: 'Read more...',
    seeLess: 'Read less...',
    descriptionFooter:'©2019 Nayomi. All Rights Reserved.',
    shopCollection:'SHOP COLLECTIONS  >',
    passwordReset:'Password Reset',
    emailAddress:'Email Address',
    mobile:'Mobile',
    Send:'Send',
    SELECT_YOUR_COUNTRY:'Select Your Country',
    INTERNATIONAL:'International',
    UAE:'UAE',
    KSA:'KSA',
    SELECT_LANGUAGE: 'Select Language',
    ARABIC:'Arabic',
    ENGLISH:'English',
    SUBMIT: 'Submit',
    needAssistance : 'Need Assistance ?',
    delivery: 'Delivery',
    delivery1: 'D E L I V E R Y',
    faq: 'FAQ',
    contactUs: 'Contact Us',
    returnsAndExchanges: 'Returns And Exchanges',
    privacyPolicy: 'Privacy Policy',
    termsAndConditions: 'Terms And Conditions',
    paymentMethods: 'Payment Methods',
    brandOverview: 'Brand Overview',
    careers: 'Careers',
    CUSTOMER_SERVICE: 'Customer Service',
    SUNDAY: 'Sunday',
    THURSDAY: 'Thursday',
    TIME: 'Time',
    AM: 'AM',
    PM: 'PM',
    CONTACT: 'Contact',
    SHIPPING: 'Shipping',
    EXPRESS: 'Express',
    DAYS: 'Days',
    FREE_DELIVERY_ON_ALL_ORDERS_ABOVE: 'Free Delivery on All Orders Above 299',
    _1_to_3: '1 to 3',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    MOBLIE: 'Mobile',
    EMAIL: 'Email',
    BIRTHDAY: 'Birthday',
    WEDDING_ANNIVERSARY: 'Wedding Anniversary',
    MANDATORY: 'Mandatory',
    REGISTER: 'Register',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    SIGN_UP: 'Sign Up',
    SIGN_IN: 'Sign In',
    CREATE_AN_ACCOUNT: 'Create an Account',
    ACCOUNT_PREFERENCES: 'Account Preferences',
    SAVE_ADDRESSES: 'Save Addresses',
    WISHLIST: 'Wishlist',
    ORDER_TRACKING: 'Order Tracking',
    SECURE_SIGN_IN: 'Secure Sign In',
    FORGOT_PASSWORD: 'Forgot Password',
    USERNAME: 'Username',
    TEXT1: 'If you have already registered with Nayomi, then sign in here.',
    TEXT2: 'Register with nayomi.com to enjoy personalized services, including:',
    REGISTERED_CUSTORMERS: 'R E G I S T E R E D  C U S T O M E R S',
    CREATE_AN_ACCOUNT1: 'C R E A T E  A N  A C C O U N T',
    checkOutAsGuest: 'C H E C K O U T  A S  A  G U E S T',
    checkOutAsGuestButton: 'Checkout as a guest',
    style:'Style',
    collection:'Collection',
    offers:'OFFERS',
    showAll:'SHOW ALL',
    login:'Login',
    search:'Search',
    productCode:'Product code',
    cancel: 'Cancel',
    save: 'Save',
    change_password: 'Change Password',
    acccount: 'Account',
    order_history: 'Order History',
    wishlist: 'Wishlist',
    logout: 'Logout',
    profile: 'P R O F I L E',
    phone_number: 'Phone Number:',
    address_book: 'A D D R E S S',
    view_all: 'View All',
    TEXT3: 'You currently have no shipping addresses setup. To add a shipping address, please',
    click_me: 'Click Me',
    your_name: 'Your Name',
    purpose: 'Purpose',
    your_comment: 'Your Comment',
    submit: 'Submit',
    write_to_us: 'W R I T E   T O   U S',
    direct_contact: 'D I R E C T   C O N T A C T',
    social_media: 'S O C I A L   M E D I A',
    TEXT4: 'Welcome. How can we help you?',
    TEXT5: 'Search your questions here...',
    sizeFit : 'Size & Fit',
    bra: 'Bra',
    panty: 'Panty',
    nightwear: 'Nightwear',
    slippers:'Slippers',
    welcomeHowcanwehelpyour: 'Welcome. How can we help your?',
    sizeGuide: 'Size Guide',
    returns: 'Returns',
    legal: 'Legal',
    unitedArabEmirates: 'United Arab Emirates',
    saudiArabia: 'Saudi Arabia',
    kuwait: 'Kuwait',
    bahrain: 'Bahrain',
    qatar: 'Qatar',
    oman: 'Oman',
    morocco: 'Morocco',
    order_number: 'O R D E R   N U M B E R',
    address: 'A D D R E S S E S',
    address1: 'Address1',
    address2: 'Address2',
    address3: 'Address3',
    addressType: 'Address Type',
    primaryAddress: 'Primary Address',
    deliver_to: 'Deliver To:',
    payment: 'P A Y M E N T',
    delivery1: 'D E L I V E R Y',
    order_summary: 'O R D E R   S U M M A R Y',
    subtotal: 'SubTotal',
    shipping: 'Shipping',
    cod: 'Cash On Delivery',
    total: 'Total',
    vat: 'VAT 5% Included',
    order_status: 'Order Status',
    pay_by_card: 'Pay By Card',
    order_status1: 'O R D E R   S T A T U S',
    payment_summary: 'P A Y M E N T   S U M M A R Y',
    saving: 'Savings',
    direction: '   Direction',
    color: 'Color',
    size: 'Size',
    qty: 'QTY',
    inStock: 'In stock',
    secureShopping:'Secure Shopping',
    cashOnDelivery:'Cash On Delivery',
    freeClickCollect:'Free Click & Collect',
    to5DaysDelivery:'3 to 5 Days Delivery',
    youMayAlsoLove: 'YOU MAY ALSO LOVE',
    bandSize: 'Band Size',
    cupSize: 'Cup Size',
    addToBag: 'ADD TO BAG',
    filterBy: 'Filter By',
    sortBy: 'Sort By',
    remove: 'Remove',
    symbol: '<',
    checkout: 'CheckOut',
    TEXT6: 'Please note, the final purchase price may change when you select your delivery address & payment method.',
    you_may_also_love: 'YOU MAY ALSO LOVE',
    bag_empty: 'Your bag is empty.',
    yes:'Yes',
    no: 'No',
    out_of_stock_items: 'OUT OF STOCK ITEMS',
    remove_these_items: 'Remove these items',
    product: 'Product',
    quantity: 'Quantity',
    status: 'Status',
    shopping_bag: 'S H O P P I N G   B A G',
    proceed: 'Proceed',
    placeOrder: 'Place Order',
    address_information: 'ADDRESS INFORMATION',
    saved_addresses: 'Saved Addresses',
    add_new_address: 'Add New Address',
    outStock: ' Out stock',
    alertQtySizeMsg1: 'This product has a maximum orderable quantity of ',
    alertQtySizeMsg2: ' Please update your selected quantity to be within this limit.To order quantity more than ',
    alertQtySizeMsg3: ' please contact us.',
    readMore: 'Read more',
    readLess: 'Read less',
    buymore_savemore:'Buy More, Save More',
    buyMore: 'Buy More,',
    saveMore: 'Save More!',
    discoverMore: 'DISCOVER MORE',
    for: 'For',
    imagePreviewNotAvailable: 'Image Preview Is not Available',
    aed: 'AED',
    sar: 'SAR',
    usd: 'USD',
    editAddress: "Edit Address",
    addAddress: "Add Address",
    addnewAddress: "Add New Shipping Address",
    delete: "Delete",
    edit: "Edit",
    updateAddressToster: "Address Updated Successfully",
    addAddressToster: "Address Added Successfully",
    deleteAddressToster: "Address Deleted Successfully",
    videoDownloaded: 'Video Downloaded Successfully',
    postal_code: 'ZIP',
    color: 'Color :',
    size: 'Size :',
    free: 'Free',
    percentageSymbol: '%',
    now: 'Now',
    was: 'Was',
    saving: 'Saving',
    shoppingBag: 'SHOPPING BAG',
    click_collect: 'CLICK & COLLECT',
    home_delivery: 'HOME DELIVERY',
    contact_information: 'CONTACT INFORMATION',
    TEXT7: 'Field marked with',
    TEXT8: 'are required',
    TEXT9: 'Any changes you make will automatically update your address book in Your Account.',
    payment1: 'Payment',
    confirmation: 'Confirmation',
    include: 'included',
    TEXT10: 'By placing your order, you agree to our',
    privacyCookiePolicy: 'Privacy & Cookie Policy',
    and: 'and',
    TEXT11: 'Unable to process your order.You can try again or contact to our customer service agent for more information..',
    TEXT12: 'We have received your order, you\'ll receive a confirmation mail soon..',
    sorry: 'Sorry',
    thankyou: 'Thank You',
    TEXT13: 'Should you have any queries, contact our customer service by calling us at +971 4 3576754 or e-mail us to customerservice@nayomi.com',
    address: 'Address',
    order_date: 'Order Date',
    order_number1: 'Order Number',
    shipping_type: 'Shipping Type',
    payment_type: 'Payment Type',
    order_total: 'Order Total',
    TEXT14: 'Your Haven\'t Purchased Anything Yet',
    more: 'more',
    remeber_me: 'Remember Me',
    sign_up_now: 'Sign Up Now!',
    sale: 'Sale',
    mada_bank_card_credit_card: 'Mada Bank Card/ Credit Card',
    notInternational: 'Not Available for International Delivery',
    registerNow: 'Register Now',
    toOurVipClub: 'To Our VIP Club',
    vipDiscount: 'VIP Discounts  |  Birthday Treats',
    privateEvents: 'Private Events & Sales  |  and Much Much More',
    ok: 'Ok',
    cancel: 'Cancel',
    signInSuccess: 'You\'ve Successfull Signed In',

};